"""Authoritative per-team logo backgrounds: the colour each tile renders on.

Every club has two committed tiles — a base (its primary colour) and an alt (a
distinct second colour). When two clubs in a matchup share a near-identical base,
one renders its alt instead so they stay distinct on a small panel. These maps are
the runtime source of truth for that decision (`delta_e` between the two clubs'
backgrounds) and they mirror the committed tiles exactly — `tests/test_mlb_palette.py`
asserts each tile's corner pixel equals its entry here, so the two cannot drift.

The colours are also the team's win-probability-meter colours: when a club shows its
alt logo its primary is "freed" for the meter, and vice versa. Several are dim
against black (navy, the Angels' blue) — the meter renderer must value-lift them to a
legibility floor, a constraint tracked for that feature, not applied to the tiles.

The tiles are generated by `tools/render_mlb_logo_variants.py` from cached MLBStatic /
Wikimedia art; this module is the typed, committed record of where each one sits.
Keyed by StatsAPI team id to join `mlb_teams._TEAM_ID_INFO`.
"""

from __future__ import annotations

from omni.core.colors import RGBColor

__all__ = ["LOGO_BASE_COLOR", "LOGO_ALT_COLOR"]

# StatsAPI team id -> the base tile background (the team's primary colour).
LOGO_BASE_COLOR: dict[int, RGBColor] = {
    108: RGBColor(186, 0, 33),  # LAA
    109: RGBColor(167, 25, 48),  # AZ
    110: RGBColor(223, 70, 1),  # BAL
    111: RGBColor(12, 35, 64),  # BOS
    112: RGBColor(14, 51, 134),  # CHC
    113: RGBColor(198, 1, 31),  # CIN
    114: RGBColor(0, 43, 92),  # CLE
    115: RGBColor(0, 0, 0),  # COL
    116: RGBColor(12, 35, 64),  # DET
    117: RGBColor(0, 45, 98),  # HOU
    118: RGBColor(1, 71, 135),  # KC
    119: RGBColor(0, 90, 156),  # LAD
    120: RGBColor(171, 0, 3),  # WSH
    121: RGBColor(0, 45, 114),  # NYM
    133: RGBColor(0, 56, 49),  # ATH
    134: RGBColor(0, 0, 0),  # PIT
    135: RGBColor(47, 36, 29),  # SD
    136: RGBColor(12, 44, 86),  # SEA
    137: RGBColor(0, 0, 0),  # SF
    138: RGBColor(190, 10, 20),  # STL
    139: RGBColor(11, 46, 93),  # TB
    140: RGBColor(0, 50, 120),  # TEX
    141: RGBColor(19, 74, 142),  # TOR
    142: RGBColor(0, 43, 92),  # MIN
    143: RGBColor(232, 24, 40),  # PHI
    144: RGBColor(19, 39, 79),  # ATL
    145: RGBColor(0, 0, 0),  # CWS
    146: RGBColor(0, 0, 0),  # MIA
    147: RGBColor(12, 35, 64),  # NYY
    158: RGBColor(19, 41, 75),  # MIL
}

# StatsAPI team id -> the alt tile background (a distinct second brand colour).
LOGO_ALT_COLOR: dict[int, RGBColor] = {
    108: RGBColor(0, 50, 99),  # LAA -> navy
    109: RGBColor(48, 206, 216),  # AZ -> teal
    110: RGBColor(0, 0, 0),  # BAL -> black
    111: RGBColor(189, 48, 57),  # BOS -> red (the hanging socks)
    112: RGBColor(204, 52, 51),  # CHC -> red
    113: RGBColor(0, 0, 0),  # CIN -> black
    114: RGBColor(227, 25, 55),  # CLE -> red
    115: RGBColor(51, 0, 111),  # COL -> purple
    116: RGBColor(250, 70, 22),  # DET -> orange
    117: RGBColor(235, 110, 31),  # HOU -> orange
    118: RGBColor(255, 199, 44),  # KC -> gold
    119: RGBColor(255, 255, 255),  # LAD -> white
    120: RGBColor(20, 34, 90),  # WSH -> navy
    121: RGBColor(255, 89, 16),  # NYM -> orange
    133: RGBColor(239, 178, 30),  # ATH -> gold
    134: RGBColor(255, 205, 0),  # PIT -> yellow
    135: RGBColor(255, 196, 37),  # SD -> gold
    136: RGBColor(0, 92, 92),  # SEA -> NW green
    137: RGBColor(239, 209, 159),  # SF -> cream
    138: RGBColor(12, 35, 64),  # STL -> navy
    139: RGBColor(143, 188, 230),  # TB -> light blue
    140: RGBColor(192, 17, 31),  # TEX -> red
    141: RGBColor(108, 172, 228),  # TOR -> light blue
    142: RGBColor(0, 154, 188),  # MIN -> vintage blue
    143: RGBColor(0, 48, 135),  # PHI -> blue
    144: RGBColor(206, 17, 65),  # ATL -> scarlet
    145: RGBColor(196, 206, 212),  # CWS -> silver
    146: RGBColor(0, 163, 224),  # MIA -> Miami blue
    147: RGBColor(196, 206, 211),  # NYY -> silver
    158: RGBColor(255, 199, 44),  # MIL -> gold
}
